import { collection, getDocs, writeBatch, doc } from "firebase/firestore";
import { db } from "../firebase";
import type {
  DeliveryOrder,
  Item,
  Job,
  PickupEvent,
  PurchaseOrder,
  StagingLocation,
  StatusHistoryEvent,
  Vendor,
} from "./models";

const jobs: Job[] = [
  {
    id: "job-1",
    jobNumber: "JOB-2026-0421",
    jobName: "Riverside Medical Center",
    siteNumber: "SITE-A3",
    status: "active",
    materialOwnerId: "owner-dispatch-1",
    materialOwnerName: "Dispatch Lead",
    createdAt: "2026-05-20T08:00:00Z",
    updatedAt: "2026-05-29T15:00:00Z",
    pinCode: "1234",
  },
  {
    id: "job-2",
    jobNumber: "JOB-2026-0389",
    jobName: "Oakwood Office Park",
    siteNumber: "SITE-B1",
    status: "active",
    createdAt: "2026-05-18T09:00:00Z",
    updatedAt: "2026-05-28T10:10:00Z",
    pinCode: "5678",
  },
  {
    id: "job-3",
    jobNumber: "JOB-2026-0450",
    jobName: "Downtown Highrise",
    siteNumber: "SITE-D4",
    status: "active",
    createdAt: "2026-05-22T13:30:00Z",
    updatedAt: "2026-05-30T09:30:00Z",
  },
];

const vendors: Vendor[] = [
  {
    id: "vendor-1",
    name: "Johnstone Supply",
    contactName: "Dispatch Desk",
    contactPhone: "555-0101",
    email: "dispatch@johnstone.com",
    emailDomain: "johnstone.com",
    pinCode: "1234",
    active: true,
    createdAt: "2026-05-01T08:00:00Z",
    updatedAt: "2026-06-08T12:00:00Z",
  },
  {
    id: "vendor-2",
    name: "First Supply",
    contactName: "Warehouse Counter",
    contactPhone: "555-0102",
    email: "counter@firstsupply.com",
    emailDomain: "firstsupply.com",
    pinCode: "2345",
    active: true,
    createdAt: "2026-05-01T08:00:00Z",
    updatedAt: "2026-06-08T12:00:00Z",
  },
  {
    id: "vendor-3",
    name: "Ferguson HVAC",
    contactName: "Commercial Team",
    contactPhone: "555-0103",
    email: "commercial@ferguson.com",
    emailDomain: "ferguson.com",
    pinCode: "3456",
    active: true,
    createdAt: "2026-05-01T08:00:00Z",
    updatedAt: "2026-06-08T12:00:00Z",
  },
];

const stagingLocations: StagingLocation[] = [
  {
    id: "staging-1",
    code: "G1",
    label: "Ground Spot 1",
    type: "ground",
    status: "Active",
    sortOrder: 1,
    widthFt: 4,
    depthFt: 4,
  },
  {
    id: "staging-2",
    code: "G2",
    label: "Ground Spot 2",
    type: "ground",
    status: "Active",
    sortOrder: 2,
    widthFt: 4,
    depthFt: 4,
  },
  {
    id: "staging-3",
    code: "S1-A",
    label: "Shelf 1 - Bin A",
    type: "shelf",
    status: "Active",
    sortOrder: 3,
    widthFt: 3,
    depthFt: 3,
  },
  {
    id: "staging-4",
    code: "S2-A",
    label: "Shelf 2 - Bin A",
    type: "shelf",
    status: "Active",
    sortOrder: 4,
    widthFt: 3,
    depthFt: 3,
  },
  {
    id: "staging-5",
    code: "GL",
    label: "Large Ground Spot",
    type: "ground",
    status: "Active",
    sortOrder: 5,
    widthFt: 4,
    depthFt: 10,
  },
];

const purchaseOrders: PurchaseOrder[] = [
  {
    id: "po-1",
    poNumber: "PO-88374",
    jobId: "job-1",
    vendorId: "vendor-1",
    orderDate: "2026-05-23",
    expectedDeliveryDate: "2026-05-30",
    status: "open",
  },
  {
    id: "po-2",
    poNumber: "PO-88375",
    jobId: "job-2",
    vendorId: "vendor-2",
    orderDate: "2026-05-22",
    expectedDeliveryDate: "2026-05-29",
    status: "partially_received",
  },
  {
    id: "po-3",
    poNumber: "PO-88377",
    jobId: "job-3",
    vendorId: "vendor-3",
    orderDate: "2026-05-24",
    expectedDeliveryDate: "2026-05-30",
    status: "open",
  },
  {
    id: "po-demo-vendor-1",
    poNumber: "PO-88390",
    jobId: "job-1",
    vendorId: "vendor-1",
    orderDate: "2026-06-02",
    expectedDeliveryDate: "2026-06-02",
    status: "open",
  },
  {
    id: "po-4",
    poNumber: "PO-88392",
    jobId: "job-2",
    vendorId: "vendor-1",
    orderDate: "2026-05-28",
    expectedDeliveryDate: "2026-06-01",
    status: "partially_received",
  },
  {
    id: "po-5",
    poNumber: "PO-88393",
    jobId: "job-3",
    vendorId: "vendor-1",
    orderDate: "2026-05-30",
    expectedDeliveryDate: "2026-06-02",
    status: "partially_received",
  },
  {
    id: "po-6",
    poNumber: "PO-88394",
    jobId: "job-2",
    vendorId: "vendor-1",
    orderDate: "2026-06-02",
    expectedDeliveryDate: "2026-06-03",
    status: "open",
  },
];

const deliveryOrders: DeliveryOrder[] = [
  {
    id: "delivery-1",
    orderNumber: "ORD-001",
    jobId: "job-1",
    vendorId: "vendor-1",
    vendorName: "Johnstone Supply",
    purchaseOrderId: "po-1",
    deliveryDate: "2026-05-30",
    stagingLocationId: "staging-2",
    status: "pending",
    issueSummary: "",
    notes: "Driver ETA after lunch.",
    createdAt: "2026-05-25T08:30:00Z",
    updatedAt: "2026-05-29T15:00:00Z",
  },
  {
    id: "delivery-2",
    orderNumber: "ORD-002",
    jobId: "job-2",
    vendorId: "vendor-1",
    vendorName: "Johnstone Supply",
    purchaseOrderId: "po-4",
    deliveryDate: "2026-06-01",
    status: "partial",
    issueSummary: "1 item backordered",
    notes:
      "Email ingest (svbotmail@gmail.com): Johnstone Reply-All SO#6163986 — Customer P/O La Crosse PF. Partial ship + line 2 backorder. Dispatcher: confirm split vs ship-complete hold.",
    createdAt: "2026-05-28T09:00:00Z",
    updatedAt: "2026-06-01T11:20:00Z",
  },
  {
    id: "delivery-3",
    orderNumber: "ORD-004",
    jobId: "job-3",
    vendorId: "vendor-1",
    vendorName: "Johnstone Supply",
    purchaseOrderId: "po-5",
    deliveryDate: "2026-06-02",
    stagingLocationId: "staging-4",
    status: "partial",
    readinessStatus: "not_ready",
    currentLocationNote: "West dock bay 3 — lift gate unload",
    availabilityStatus: "received",
    issueSummary: "Received qty below vendor ship qty",
    notes:
      "Email ingest (svbotmail@gmail.com): Johnstone Reply-All SO#6164304 claimed 3× thermostat shipped; shop receipt shows 2. Dispatcher: reconcile lines before readiness.",
    createdAt: "2026-05-30T14:00:00Z",
    updatedAt: "2026-06-02T07:45:00Z",
  },
  {
    id: "delivery-demo-vendor-1",
    orderNumber: "ORD-005",
    jobId: "job-1",
    vendorId: "vendor-1",
    vendorName: "Johnstone Supply",
    purchaseOrderId: "po-demo-vendor-1",
    deliveryDate: "2026-06-02",
    stagingLocationId: "staging-1",
    plannedStagingLocationIds: ["staging-1", "staging-2", "staging-3"],
    status: "pending",
    issueSummary: "",
    notes:
      "Email ingest (svbotmail@gmail.com): Johnstone will-call SO#6164159 — Customer P/O PLANET FITNESS PICKUP. Vendor demo QR unchanged. Assign staging when material arrives (orange row).",
    createdAt: "2026-06-02T12:00:00Z",
    updatedAt: "2026-06-02T12:00:00Z",
  },
  {
    id: "delivery-demo-vendor-2",
    orderNumber: "ORD-006",
    jobId: "job-2",
    vendorId: "vendor-1",
    vendorName: "Johnstone Supply",
    purchaseOrderId: "po-6",
    deliveryDate: "2026-06-03",
    plannedStagingLocationIds: ["staging-4", "staging-5"],
    status: "shipped",
    issueSummary: "",
    notes:
      "Email ingest (svbotmail@gmail.com): Johnstone Reply-All SO#6164100 — Customer P/O TRUCK STOCK PICKUP shipped on truck. Driver ETA 2–4 pm. Assign staging before check-in.",
    createdAt: "2026-06-02T16:00:00Z",
    updatedAt: "2026-06-03T06:30:00Z",
  },
  {
    id: "delivery-cross-vendor-1",
    orderNumber: "ORD-007",
    jobId: "job-3",
    vendorId: "vendor-3",
    vendorName: "Ferguson HVAC",
    purchaseOrderId: "po-3",
    deliveryDate: "2026-06-02",
    stagingLocationId: "staging-2",
    plannedStagingLocationIds: ["staging-2"],
    status: "pending",
    issueSummary: "",
    notes: "Ferguson cross-vendor fixture — must stay absent for job-1 PIN (D14).",
    createdAt: "2026-06-02T14:00:00Z",
    updatedAt: "2026-06-02T14:00:00Z",
  },
];

const items: Item[] = [
  {
    id: "item-1",
    deliveryOrderId: "delivery-1",
    sku: "RTU-5T",
    description: "RTU 5-ton package unit",
    qtyOrdered: 2,
    qtyReceived: 0,
    qtyMissing: 2,
    qtyDamaged: 0,
    qtyBackordered: 0,
    status: "pending",
  },
  {
    id: "item-2",
    deliveryOrderId: "delivery-1",
    sku: "DCT-2412",
    description: "Ductwork section 24x12",
    qtyOrdered: 4,
    qtyReceived: 0,
    qtyMissing: 4,
    qtyDamaged: 0,
    qtyBackordered: 0,
    status: "pending",
  },
  {
    id: "item-3",
    deliveryOrderId: "delivery-2",
    sku: "NS10762605",
    description: "GREENHECK FAN 105105",
    qtyOrdered: 1,
    qtyReceived: 1,
    qtyMissing: 0,
    qtyDamaged: 0,
    qtyBackordered: 0,
    status: "received",
  },
  {
    id: "item-4",
    deliveryOrderId: "delivery-2",
    sku: "NS99999999",
    description: "BACKORDERED PART — 2 DAY LEAD",
    qtyOrdered: 1,
    qtyReceived: 0,
    qtyMissing: 1,
    qtyDamaged: 0,
    qtyBackordered: 1,
    status: "backordered",
  },
  {
    id: "item-6",
    deliveryOrderId: "delivery-3",
    sku: "L46-668",
    description: "TH8320R1003/U THERMOSTAT PROGRAMMABLE REDLINK",
    qtyOrdered: 3,
    qtyReceived: 2,
    qtyMissing: 1,
    qtyDamaged: 0,
    qtyBackordered: 0,
    status: "partial",
    materialSource: "vendor_delivery",
    availabilityStatus: "received",
  },
  {
    id: "item-7",
    deliveryOrderId: "delivery-3",
    sku: "B86-380",
    description: "4050-08 SEALANT REFRIGERATIO EASYSEAL",
    qtyOrdered: 1,
    qtyReceived: 1,
    qtyMissing: 0,
    qtyDamaged: 0,
    qtyBackordered: 0,
    status: "received",
  },
  {
    id: "item-demo-v1-1",
    deliveryOrderId: "delivery-demo-vendor-1",
    sku: "L46-668",
    description: "TH8320R1003/U THERMOSTAT PROGRAMMABLE REDLINK",
    qtyOrdered: 1,
    qtyReceived: 0,
    qtyMissing: 1,
    qtyDamaged: 0,
    qtyBackordered: 0,
    status: "pending",
  },
  {
    id: "item-demo-v1-2",
    deliveryOrderId: "delivery-demo-vendor-1",
    sku: "B86-380",
    description: "4050-08 SEALANT REFRIGERATIO EASYSEAL",
    qtyOrdered: 6,
    qtyReceived: 0,
    qtyMissing: 6,
    qtyDamaged: 0,
    qtyBackordered: 0,
    status: "pending",
  },
  {
    id: "item-demo-v1-3",
    deliveryOrderId: "delivery-demo-vendor-1",
    sku: "L46-100",
    description: "TEST-001 FILTER DRIER",
    qtyOrdered: 2,
    qtyReceived: 0,
    qtyMissing: 2,
    qtyDamaged: 0,
    qtyBackordered: 0,
    status: "pending",
  },
  {
    id: "item-demo-v2-1",
    deliveryOrderId: "delivery-demo-vendor-2",
    sku: "L46-100",
    description: "TEST-001 FILTER DRIER",
    qtyOrdered: 1,
    qtyReceived: 0,
    qtyMissing: 1,
    qtyDamaged: 0,
    qtyBackordered: 0,
    status: "pending",
  },
];

const statusHistory: StatusHistoryEvent[] = [
  {
    id: "event-1",
    entityType: "delivery_order",
    entityId: "delivery-1",
    toStatus: "pending",
    actorType: "dispatcher",
    actorName: "Gavin",
    createdAt: "2026-05-25T08:30:00Z",
  },
  {
    id: "event-2",
    entityType: "delivery_order",
    entityId: "delivery-2",
    fromStatus: "arrived",
    toStatus: "partial",
    reason: "Backordered line per Johnstone Reply-All SO#6163986",
    actorType: "vendor",
    actorName: "Johnstone Sioux Falls",
    createdAt: "2026-06-01T11:20:00Z",
  },
  {
    id: "event-3",
    entityType: "item",
    entityId: "item-4",
    fromStatus: "pending",
    toStatus: "backordered",
    reason: "2 DAY LEAD — Johnstone email line 2",
    actorType: "vendor",
    actorName: "Johnstone Sioux Falls",
    createdAt: "2026-06-01T11:19:00Z",
  },
  {
    id: "event-4",
    entityType: "delivery_order",
    entityId: "delivery-3",
    fromStatus: "pending",
    toStatus: "arrived",
    actorType: "vendor",
    actorName: "Johnstone Sioux Falls",
    createdAt: "2026-06-02T07:45:00Z",
  },
  {
    id: "event-demo-vendor-1",
    entityType: "delivery_order",
    entityId: "delivery-demo-vendor-1",
    toStatus: "pending",
    actorType: "dispatcher",
    actorName: "Gavin",
    createdAt: "2026-06-02T12:00:00Z",
  },
  {
    id: "event-demo-vendor-2-pending",
    entityType: "delivery_order",
    entityId: "delivery-demo-vendor-2",
    toStatus: "pending",
    actorType: "dispatcher",
    actorName: "Gavin",
    createdAt: "2026-06-02T16:00:00Z",
  },
  {
    id: "event-demo-vendor-2-shipped",
    entityType: "delivery_order",
    entityId: "delivery-demo-vendor-2",
    fromStatus: "pending",
    toStatus: "shipped",
    actorType: "dispatcher",
    actorName: "Gavin",
    createdAt: "2026-06-03T06:30:00Z",
  },
];

const pickupEvents: PickupEvent[] = [
  {
    id: "pickup-1",
    deliveryOrderId: "delivery-2",
    jobId: "job-2",
    technicianName: "A. Miller",
    pickedUpAt: "2026-06-01T08:15:00Z",
    itemsPickedSummary: "1× GREENHECK FAN (partial ship line)",
    notes: "Backordered part still on Johnstone hold",
  },
];

export async function seedFirestore(): Promise<void> {
  const snap = await getDocs(collection(db, "deliveries"));
  if (!snap.empty) return;

  console.log("Seeding Firestore with demo data...");
  const batch = writeBatch(db);

  const seed = <T extends { id: string }>(colName: string, arr: T[]) => {
    for (const item of arr) {
      batch.set(doc(db, colName, item.id), item);
    }
  };

  seed("deliveries", deliveryOrders);
  seed("items", items);
  seed("jobs", jobs);
  seed("vendors", vendors);
  seed("stagingLocations", stagingLocations);
  seed("statusHistory", statusHistory);
  seed("pickupEvents", pickupEvents);
  seed("purchaseOrders", purchaseOrders);

  await batch.commit();
  console.log("Firestore seeded.");
}
