import type { Order, StagingZone, ConfirmationLog } from "./types";

export const stagingZones: StagingZone[] = [
  {
    id: "G1",
    label: "Ground Spot 1",
    description: "Ground staging spot — near roll-up door",
    currentOrderId: "ORD-003",
  },
  {
    id: "G2",
    label: "Ground Spot 2",
    description: "Ground staging spot — center bay",
    currentOrderId: "ORD-001",
  },
  {
    id: "G3",
    label: "Ground Spot 3",
    description: "Ground staging spot — far wall",
    currentOrderId: null,
  },
  {
    id: "S1-A",
    label: "Shelf 1 · Bin A",
    description: "Shelf unit 1, top bin A",
    currentOrderId: "ORD-002",
  },
  {
    id: "S1-B",
    label: "Shelf 1 · Bin B",
    description: "Shelf unit 1, lower bin B",
    currentOrderId: null,
  },
  {
    id: "S2-A",
    label: "Shelf 2 · Bin A",
    description: "Shelf unit 2, top bin A",
    currentOrderId: "ORD-004",
  },
];

export const mockOrders: Order[] = [
  {
    id: "ORD-001",
    vendor: "Johnstone Supply",
    jobName: "Riverside Medical Center",
    jobNumber: "JOB-2026-0421",
    siteNumber: "SITE-A3",
    zoneId: "G2",
    status: "Pending",
    items: [
      {
        id: "itm-1",
        description: "RTU 5-ton package unit",
        quantity: 2,
        deliveredQty: 0,
        missingQty: 0,
        status: null,
      },
      {
        id: "itm-2",
        description: "Ductwork section 24×12",
        quantity: 4,
        deliveredQty: 0,
        missingQty: 0,
        status: null,
      },
      {
        id: "itm-3",
        description: "Return air grille 20×20",
        quantity: 6,
        deliveredQty: 0,
        missingQty: 0,
        status: null,
      },
    ],
    createdAt: "2026-05-25T08:30:00Z",
    confirmedAt: null,
  },
  {
    id: "ORD-002",
    vendor: "First Supply",
    jobName: "Oakwood Office Park",
    jobNumber: "JOB-2026-0389",
    siteNumber: "SITE-B1",
    zoneId: "S1-A",
    status: "Partial",
    items: [
      {
        id: "itm-4",
        description: "Condenser coil 3-ton",
        quantity: 1,
        deliveredQty: 1,
        missingQty: 0,
        status: "Delivered",
      },
      {
        id: "itm-5",
        description: "Line set 50′ 3/8-7/8",
        quantity: 2,
        deliveredQty: 2,
        missingQty: 0,
        status: "Delivered",
      },
      {
        id: "itm-6",
        description: "Thermostat T10 Pro",
        quantity: 1,
        deliveredQty: 0,
        missingQty: 1,
        status: "Backordered",
      },
    ],
    createdAt: "2026-05-24T14:15:00Z",
    confirmedAt: "2026-05-25T09:45:00Z",
    vendorNote: "Thermostat on backorder — expected next week.",
  },
  {
    id: "ORD-003",
    vendor: "Carrier HVAC Supply",
    jobName: "Pinebrook Apartments",
    jobNumber: "JOB-2026-0410",
    siteNumber: "SITE-C2",
    zoneId: "G1",
    status: "Complete",
    items: [
      {
        id: "itm-7",
        description: "Furnace 80k BTU gas",
        quantity: 3,
        deliveredQty: 3,
        missingQty: 0,
        status: "Delivered",
      },
      {
        id: "itm-8",
        description: "Evaporator coil cased",
        quantity: 3,
        deliveredQty: 3,
        missingQty: 0,
        status: "Delivered",
      },
      {
        id: "itm-9",
        description: "Filter rack 16×25",
        quantity: 3,
        deliveredQty: 3,
        missingQty: 0,
        status: "Delivered",
      },
    ],
    createdAt: "2026-05-23T10:00:00Z",
    confirmedAt: "2026-05-24T16:20:00Z",
  },
  {
    id: "ORD-004",
    vendor: "Ferguson HVAC",
    jobName: "Downtown Highrise",
    jobNumber: "JOB-2026-0450",
    siteNumber: "SITE-D4",
    zoneId: "S2-A",
    status: "Pending",
    items: [
      {
        id: "itm-10",
        description: "Chiller 50-ton modular",
        quantity: 1,
        deliveredQty: 0,
        missingQty: 0,
        status: null,
      },
      {
        id: "itm-11",
        description: "Cooling tower fill pack",
        quantity: 2,
        deliveredQty: 0,
        missingQty: 0,
        status: null,
      },
      {
        id: "itm-12",
        description: "Pump circulator 5HP",
        quantity: 2,
        deliveredQty: 0,
        missingQty: 0,
        status: null,
      },
    ],
    createdAt: "2026-05-25T07:00:00Z",
    confirmedAt: null,
  },
];

export const mockConfirmations: ConfirmationLog[] = [
  {
    id: "LOG-001",
    orderId: "ORD-002",
    vendor: "First Supply",
    jobName: "Oakwood Office Park",
    jobNumber: "JOB-2026-0389",
    siteNumber: "SITE-B1",
    zoneId: "S1-A",
    status: "Partial",
    confirmedAt: "2026-05-25T09:45:00Z",
    items: [
      {
        id: "itm-4",
        description: "Condenser coil 3-ton",
        quantity: 1,
        deliveredQty: 1,
        missingQty: 0,
        status: "Delivered",
      },
      {
        id: "itm-5",
        description: "Line set 50′ 3/8-7/8",
        quantity: 2,
        deliveredQty: 2,
        missingQty: 0,
        status: "Delivered",
      },
      {
        id: "itm-6",
        description: "Thermostat T10 Pro",
        quantity: 1,
        deliveredQty: 0,
        missingQty: 1,
        status: "Backordered",
      },
    ],
    vendorNote: "Thermostat on backorder — expected next week.",
  },
  {
    id: "LOG-002",
    orderId: "ORD-003",
    vendor: "Carrier HVAC Supply",
    jobName: "Pinebrook Apartments",
    jobNumber: "JOB-2026-0410",
    siteNumber: "SITE-C2",
    zoneId: "G1",
    status: "Complete",
    confirmedAt: "2026-05-24T16:20:00Z",
    items: [
      {
        id: "itm-7",
        description: "Furnace 80k BTU gas",
        quantity: 3,
        deliveredQty: 3,
        missingQty: 0,
        status: "Delivered",
      },
      {
        id: "itm-8",
        description: "Evaporator coil cased",
        quantity: 3,
        deliveredQty: 3,
        missingQty: 0,
        status: "Delivered",
      },
      {
        id: "itm-9",
        description: "Filter rack 16×25",
        quantity: 3,
        deliveredQty: 3,
        missingQty: 0,
        status: "Delivered",
      },
    ],
  },
];

/* ── Zone naming reference ── */
export const zoneNamingReference: Record<string, string> = {
  G1: "Ground staging spot 1",
  G2: "Ground staging spot 2",
  G3: "Ground staging spot 3",
  "S1-A": "Shelf 1, Bin A",
  "S1-B": "Shelf 1, Bin B",
  "S2-A": "Shelf 2, Bin A",
};
