import type { Order, StagingZone, ConfirmationLog } from "./types";

export const stagingZones: StagingZone[] = [
  {
    id: "G21",
    label: "Zone G21",
    description: "Loading dock west, bay 21",
    currentOrderId: "ORD-001",
  },
  {
    id: "A14",
    label: "Zone A14",
    description: "Receiving area north, bay 14",
    currentOrderId: "ORD-002",
  },
  {
    id: "B7",
    label: "Zone B7",
    description: "Receiving area south, bay 7",
    currentOrderId: null,
  },
];

export const mockOrders: Order[] = [
  {
    id: "ORD-001",
    vendor: "Carrier HVAC Supply",
    jobName: "Riverside Medical Center",
    jobNumber: "JOB-2026-0421",
    siteNumber: "SITE-A3",
    zoneId: "G21",
    status: "Pending",
    items: [
      {
        id: "itm-1",
        description: "RTU 5-ton package unit",
        quantity: 2,
        deliveredQty: 0,
        missingQty: 0,
        status: null,
      },
      {
        id: "itm-2",
        description: "Ductwork section 24x12",
        quantity: 4,
        deliveredQty: 0,
        missingQty: 0,
        status: null,
      },
      {
        id: "itm-3",
        description: "Return air grille 20x20",
        quantity: 6,
        deliveredQty: 0,
        missingQty: 0,
        status: null,
      },
    ],
    createdAt: "2026-05-25T08:30:00Z",
    confirmedAt: null,
  },
  {
    id: "ORD-002",
    vendor: "Ferguson HVAC",
    jobName: "Oakwood Office Park",
    jobNumber: "JOB-2026-0389",
    siteNumber: "SITE-B1",
    zoneId: "A14",
    status: "Partial",
    items: [
      {
        id: "itm-4",
        description: "Condenser coil 3-ton",
        quantity: 1,
        deliveredQty: 1,
        missingQty: 0,
        status: "Delivered",
      },
      {
        id: "itm-5",
        description: "Line set 50ft 3/8-7/8",
        quantity: 2,
        deliveredQty: 2,
        missingQty: 0,
        status: "Delivered",
      },
      {
        id: "itm-6",
        description: "Thermostat T10 Pro",
        quantity: 1,
        deliveredQty: 0,
        missingQty: 1,
        status: "Backordered",
      },
    ],
    createdAt: "2026-05-24T14:15:00Z",
    confirmedAt: "2026-05-25T09:45:00Z",
    vendorNote: "Thermostat on backorder — expected next week.",
  },
  {
    id: "ORD-003",
    vendor: "Johnstone Supply",
    jobName: "Pinebrook Apartments",
    jobNumber: "JOB-2026-0410",
    siteNumber: "SITE-C2",
    zoneId: "G21",
    status: "Complete",
    items: [
      {
        id: "itm-7",
        description: "Furnace 80k BTU gas",
        quantity: 3,
        deliveredQty: 3,
        missingQty: 0,
        status: "Delivered",
      },
      {
        id: "itm-8",
        description: "Evaporator coil cased",
        quantity: 3,
        deliveredQty: 3,
        missingQty: 0,
        status: "Delivered",
      },
      {
        id: "itm-9",
        description: "Filter rack 16x25",
        quantity: 3,
        deliveredQty: 3,
        missingQty: 0,
        status: "Delivered",
      },
    ],
    createdAt: "2026-05-23T10:00:00Z",
    confirmedAt: "2026-05-24T16:20:00Z",
  },
  {
    id: "ORD-004",
    vendor: "Carrier HVAC Supply",
    jobName: "Downtown Highrise",
    jobNumber: "JOB-2026-0450",
    siteNumber: "SITE-D4",
    zoneId: "B7",
    status: "Pending",
    items: [
      {
        id: "itm-10",
        description: "Chiller 50-ton modular",
        quantity: 1,
        deliveredQty: 0,
        missingQty: 0,
        status: null,
      },
      {
        id: "itm-11",
        description: "Cooling tower fill pack",
        quantity: 2,
        deliveredQty: 0,
        missingQty: 0,
        status: null,
      },
      {
        id: "itm-12",
        description: "Pump circulator 5HP",
        quantity: 2,
        deliveredQty: 0,
        missingQty: 0,
        status: null,
      },
    ],
    createdAt: "2026-05-25T07:00:00Z",
    confirmedAt: null,
  },
];

export const mockConfirmations: ConfirmationLog[] = [
  {
    id: "LOG-001",
    orderId: "ORD-002",
    vendor: "Ferguson HVAC",
    jobName: "Oakwood Office Park",
    jobNumber: "JOB-2026-0389",
    siteNumber: "SITE-B1",
    zoneId: "A14",
    status: "Partial",
    confirmedAt: "2026-05-25T09:45:00Z",
    items: [
      {
        id: "itm-4",
        description: "Condenser coil 3-ton",
        quantity: 1,
        deliveredQty: 1,
        missingQty: 0,
        status: "Delivered",
      },
      {
        id: "itm-5",
        description: "Line set 50ft 3/8-7/8",
        quantity: 2,
        deliveredQty: 2,
        missingQty: 0,
        status: "Delivered",
      },
      {
        id: "itm-6",
        description: "Thermostat T10 Pro",
        quantity: 1,
        deliveredQty: 0,
        missingQty: 1,
        status: "Backordered",
      },
    ],
    vendorNote: "Thermostat on backorder — expected next week.",
  },
  {
    id: "LOG-002",
    orderId: "ORD-003",
    vendor: "Johnstone Supply",
    jobName: "Pinebrook Apartments",
    jobNumber: "JOB-2026-0410",
    siteNumber: "SITE-C2",
    zoneId: "G21",
    status: "Complete",
    confirmedAt: "2026-05-24T16:20:00Z",
    items: [
      {
        id: "itm-7",
        description: "Furnace 80k BTU gas",
        quantity: 3,
        deliveredQty: 3,
        missingQty: 0,
        status: "Delivered",
      },
      {
        id: "itm-8",
        description: "Evaporator coil cased",
        quantity: 3,
        deliveredQty: 3,
        missingQty: 0,
        status: "Delivered",
      },
      {
        id: "itm-9",
        description: "Filter rack 16x25",
        quantity: 3,
        deliveredQty: 3,
        missingQty: 0,
        status: "Delivered",
      },
    ],
  },
];
